### ISSUE TITLE
废话般的神贴

### ISSUE THREAD

**Issue by lsdlab** [shengcaishizhan/kkndme_tianya#30]
废话般把简单的东西说了一堆，道理我都懂，房子和房子的差别是很大的，我没见过没房的喊着要打压房价，跌成狗才好，嘿，没听说过

**Comment by ballackCaptian** [comment]
感觉主要还是把一些常识比较系统的汇总了。

**Comment by rick-lzr** [comment]
看看作者发布时间再说话。
在当时又有多少人不相信房价。这又何来的废话。

**Comment by Dowgen** [comment]
LZ拿着自己知道的近十年房产现状 和 嚼烂了N手的信息，来说 十年前的信息来源鼻祖 说的是废话

**Comment by HwiLu** [comment]
> LZ拿着自己知道的近十年房产现状 和 嚼烂了N手的信息，来说 十年前的信息来源鼻祖 说的是废话

你这句话我居然读了两遍才看懂骂的是谁
